### ISSUE TITLE
Read the docs build bug if sphinx == 5.1.1; passes w/ sphinx == 4.5.0

### ISSUE THREAD

**Issue by bendhouseart** [sphinx-contrib/matlabdomain#148]
Hey all, I was trying to streamline my build on read the docs yesterday and came across this error in the process:

```
latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v5.1.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/registry.py", line 442, in load_extension
    mod = import_module(extname)
  File "/home/docs/.asdf/installs/python/3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinxcontrib/matlab.py", line 12, in <module>
    from . import mat_documenters as doc
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinxcontrib/mat_documenters.py", line 27, in <module>
    from sphinx.ext.autodoc import py_ext_sig_re as mat_ext_sig_re, \
ImportError: cannot import name 'members_set_option' from 'sphinx.ext.autodoc' (/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 222, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 400, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/registry.py", line 445, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinxcontrib.matlab (exception: cannot import name 'members_set_option' from 'sphinx.ext.autodoc' (/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py))

Extension error:
Could not import extension sphinxcontrib.matlab (exception: cannot import name 'members_set_option' from 'sphinx.ext.autodoc' (/home/docs/checkouts/readthedocs.org/user_builds/pet2bids/envs/latest/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py))
```

Was able to remedy by setting `sphinx="<4.5.0"` in my dependencies. I had previously not even had `sphinx` listed or set, but after inspecting the last passing build decided to roll back to the version of `sphinx` echo'ed in the build output.

Let me know if there's anything I can help with in demonstrating or elaborating on.

**Comment by joeced** [comment]
I can't see which version of `sphinxcontrib-matlabdomain` it is using. It needs to be at least `>=0.14.0`

**Comment by joeced** [comment]
Can't reproduce
