### ISSUE TITLE
Exception Comments must be indeneted after make html

### ISSUE THREAD

**Issue by joeced** [sphinx-contrib/matlabdomain#45]
Originally reported by: **IshmaelBelghazi (Bitbucket: [IshmaelBelghazi](https://bitbucket.org/IshmaelBelghazi), GitHub: [IshmaelBelghazi](https://github.com/IshmaelBelghazi))**

----------------------------------------

Full Traceback:

```
#!python

# Sphinx version: 1.3.1
# Python version: 2.7.9 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   Running Sphinx v1.3.1
#   loading pickled environment...
#   done
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 0 source files that are out of date
#   updating environment:
#   [config changed] 2 added, 0 changed, 0 removed
#   reading sources... [ 50%] api
# Loaded extensions:
#   sphinx.ext.autodoc (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.intersphinx (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
#   sphinxcontrib.matlab (unknown version) from /home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/matlab.pyc
#   sphinx.ext.doctest (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   sphinx.ext.mathjax (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   sphinx.ext.viewcode (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.coverage (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   alabaster (0.7.6) from /home/ishmael/.local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.todo (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.ifconfig (1.3.1) from /home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
Traceback (most recent call last):
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/environment.py", line 126, in read
    self.parse()
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/ishmael/.local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 1467, in run
    documenter.generate(more_content=self.content)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_documenters.py", line 419, in generate
    self.analyzer.find_attr_docs()
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 1091, in find_attr_docs
    for k, v in mod.safe_getmembers():
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 229, in safe_getmembers
    value = self.getter(key, None)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 283, in getter
    attr = MatObject.matlabify('.'.join([self.package, name]))
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 133, in matlabify
    return MatObject.parse_mfile(mfile, name, path)  # parse mfile
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 184, in parse_mfile
    return MatClass(name, modname, tks)
  File "/home/ishmael/.local/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 659, in __init__
    raise Exception('Comments must be indented.')
Exception: Comments must be indented.

```

----------------------------------------
- Bitbucket: https://bitbucket.org/bwanamarko/sphinxcontrib-matlabdomain/issue/40

**Comment by joeced** [comment]
Duplicate of #19
